# Settings file for existing kits implemented in Village Defense 5
# You can translate and configure the kits here

Knight:
  Language:
    Name: "&2Knight"
    Description:
      - "This is the one and only knight kit!"
      - "Many people think this is the worst kit!"
      - "I must admit they are totally wrong!"

Cleaner:
  Language:
    Name: "&bCleaner"
    Description:
      - "&6&lGAME POWER: &7poor/&7strong/&7mediocre"
      - "&6&lCLASS: &7mixed, support/&7damage dealer"
      - ""
      - "&6&lABILITIES:"
      - "&a&l• POP AWE (PASSIVE):"
      - "  &7Every 5 seconds pop random"
      - "  &71/2/3 alive zombies"
      - "&a&l• CLEANSING STICK:"
      - "  &7On use pop random 10/20/25"
      - "  &7alive zombies with a delay"
      - "  &7of 0.5s every 5 pops"
      - "  &7(&c&lCOOLDOWN 45/&c&l35/&c&l30s&7)"
      - "&e&l• POPLUST (ULTIMATE)"
      - "  &7On use every enemy can be"
      - "  &7oneshot and popped by anyone"
      - "  &7(&c&lCAST TIME -/&c&l5&7/&c&l7s&7, &c&lCOOLDOWN 70s&7)"
      - "  &7(&c&lUNLOCKED IN MID GAME&7)"
    Game-Item:
      Cleansing-Stick:
        Name: "&6&lCLEANSING STICK"
        Description:
          - "On use pop random 10/20/25"
          - "alive zombies with a delay"
          - "of 0.5s every 5 pops"
          - "&c&lCOOLDOWN: &745/&735/&730s"
        Activate: "&7Lets wipe them up!"
      Poplust:
        Name: "&e&lPOPLUST &7(Ultimate)"
        Description:
          - "On use every enemy can be"
          - "oneshot and popped by anyone"
          - "&c&lCAST TIME: &7-/&75/&77s, &c&lCOOLDOWN &760s"
        Activate: "&7Poplust incoming!"
        Active-Title: "0,20,0;;&e&lONESHOT ENEMIES NOW!"
        Active-Action-Bar:
          - "&e&lPOPLUST ACTIVE &7(%number%s)"
          - "&c&lPOPLUST ACTIVE &7(%number%s)"
